#                                                            Developed by Senkex
#                                                        (Nautic Studios @ (C) 2026)

name: ApoloLangs
version: '${version}'
authors:
  - 'Senkex'
  - 'Nautic Studios'

api-version: '1.20'
main: com.github.nautic.ApoloLangs
website: "https://github.com/nautic-studios/ApoloLangs"

depend:
  - PlaceholderAPI

commands:
  apololangs:
    description: 'Original command'
    aliases:
      - apl
      - alangs